function figure_summary

data_folder = '../sim_data/sim_output/1/'
status_files = {'hs_1_time_step_301.json', 'hs_1_time_step_7301.json'};
t_ticks = [0.1 0.6 ; 7.1 7.6 ; 7.78 7.95];
f_scaling_factor = 0.001;
output_file_string = 'figure_isotypes';
output_types = {'eps','png'};

y_label_offsets = [-0.35, -0.8]
trace_line_width = 1.5;

left_pads = repmat([1.1, 0.2], [1 6]);
right_pads = repmat([0.2, 0.3], [1 6]);
individual_panel_labels = repmat({''}, [1 12]);
individual_panel_labels{1} = 'A';
individual_panel_labels{5} = 'B';
individual_panel_labels{11} = 'C';

colors = return_matplotlib_default_colors;
cm = colors([3 5], :);

sp = initialise_publication_quality_figure( ...
        'no_of_panels_wide', 2, ...
        'no_of_panels_high', 6, ...
        'omit_panels', [2, 4, 12], ...
        'relative_row_heights', [0.5 0.5 0.7 1 0.7 1], ...
        'left_subplot_adjustments', [0 0 0 0 0 0 0 0 0 0 0 0 0], ...
        'right_subplot_adjustments', [-1.2 0 -1.20 0 0 0 0 0 0 0 -1.2 0], ...
        'individual_padding', 1, ...
        'left_pads', left_pads, ...
        'right_pads', right_pads, ...
        'axes_padding_top', [0.3, 0.1, 0.3, 0.1, 0.1, 0.2], ...
        'axes_padding_bottom', [0.0 0.2 0.0 0.4 0.4 0.4], ...
        'individual_panel_labels', individual_panel_labels, ...
        'bottom_margin', 0);

% Draw enzyme activities
x = 0:1100;
kinase = 5 * exp(-0.002*(1100-x));
fwhm = 100;
c = fwhm / 2.3548
phosphatase = 10 * exp(-power(x-200, 2.0) ./(2*(c^2)));
subplot(sp(1));
h(1) = plot(x, kinase, '-', 'Color', colors(1,:), ...
    'linewidth', trace_line_width)
h(2) = plot(x, phosphatase, '-', 'Color', colors(2,:), ...
    'linewidth', trace_line_width)

improve_axes( ...
    'x_ticks', [0 1100], ...
    'y_ticks', [0 10], ...
    'x_axis_off', 1, ...
    'y_axis_label', {'Rate','(s^{-1})'}, ...
    'y_label_offset', y_label_offsets(1), ...
    'y_tick_decimal_places', 0)

legendflex(h, {'Kinase', 'Phosphatase'}, ...
    'title', 'Activity', ...
    'anchor',{'n','s'}, ...
    'xscale', 0.2, ...
    'padding', [3 3 4], ...
    'buffer', [10 -17])

% Draw sarcomere
subplot(sp(3))
patch([0 0 50 50 0], [0 1 1 0 0], 'k');
patch([1050 1050 1100 1100 1050], [0 1 1 0 0], 'k');
patch([0 0 1000 1000 0], [0.15 0.3 0.3 0.15 0.15], 'k');
patch([300 300 1100 1100 300], [0.5 0.85 0.85 0.5 0.5], 'k');

improve_axes( ...
    'x_ticks', [0 1100], ...
    'x_axis_offset', 0.3, ...
    'x_tick_decimal_places', 0, ...
    'x_axis_label', 'Position (nm)', ...
    'x_label_offset', -0.5, ...
    'y_ticks', [0 1], ...
    'y_axis_off', 1)

for i = 1 : 2
    fs = fullfile(data_folder, ...
            sprintf('sim_prot_1_%i_r1.txt', i));
    
    for j = 1 : 2
        % Read file and prune
        d = readtable(fs);
        vi = find((d.time >= t_ticks(j,1)) & ...
                    (d.time <= t_ticks(j,2)));
        d = d(vi,:);
    
        subplot(sp(4+j));
        h_temp = plot(d.time, f_scaling_factor * d.hs_1_force, '-', 'Color', cm(i,:), ...
                'linewidth', trace_line_width);
        if (j==1)
            h(i) = h_temp;
        end

        subplot(sp(6+j));
        plot(d.time, d.hs_1_length, '-', 'Color', cm(i,:), ...
                'linewidth', trace_line_width);

        % Find the status_files
        status_file = fullfile(data_folder, ...
                        sprintf('status_dumps_1_%i_r1', i), ...
                        status_files{j});

        s = readstruct(status_file);
        iso = [];
        for k = 1 : numel(s.thick)
            if ((k==1) & (j==1))
                cb_x = mean(reshape(s.thick(k).cb_x, 6, []));
            end
            iso = [iso ; mean(reshape(s.thick(k).cb_iso, 6, []))];
        end
        iso = mean(iso) - 1;

        subplot(sp(8+j));
        plot(cb_x, iso, '-', 'Color', cm(i,:), ...
                'linewidth', trace_line_width)
    end

    % Isometric twitch
    d = readtable(fs);
    vi = find((d.time >= t_ticks(3,1)) & ...
                (d.time <= t_ticks(3,2)));
    d = d(vi,:);

    subplot(sp(11));
    hold on;
    plot(d.time, f_scaling_factor * d.hs_1_force, '-', 'Color', cm(i,:), ...
        'linewidth', trace_line_width);
end

for i = 1 : 2
    improve_axes( ...
        'axis_handle', sp(4+i), ...
        'x_ticks', t_ticks(i,:), ...
        'x_axis_off', 1, ...
        'y_ticks', [0 120], ...
        'y_tick_decimal_places', 0, ...
        'y_axis_label', {'Stress', '(kN m^{-2})'}, ...
        'y_label_offset', y_label_offsets(2), ...
        'y_axis_off', (i==2));

    improve_axes( ...
        'axis_handle', sp(6+i), ...
        'x_ticks', t_ticks(i,:), ...
        'x_axis_label', 'Time (s)', ...
        'x_tick_decimal_places', 2, ...
        'x_label_offset', -0.4, ...
        'y_ticks', [800 1100], ...
        'y_tick_decimal_places', 0, ...
        'y_axis_label', {'Half', 'sarcomere', 'length', '(nm)'}, ...
        'y_label_offset', y_label_offsets(2), ...
        'y_axis_off', (i==2));

    improve_axes( ...
        'axis_handle', sp(8+i), ...
        'x_ticks', [0 1100], ....
        'x_tick_decimal_places', 0, ...
        'x_axis_label', 'Position (nm)', ...
        'x_label_offset', -0.6, ...
        'y_ticks', [0 1], ...
        'y_tick_decimal_places', 0, ...
        'y_axis_label', {'Relative', 'myosin','phospho-','rylation'}, ...
        'y_label_offset', y_label_offsets(2), ...
        'y_axis_off', (i==2));
end

improve_axes( ...
        'axis_handle', sp(11), ...
        'x_ticks', t_ticks(3,:), ...
        'x_axis_label', 'Time (s)', ...
        'x_tick_decimal_places', 2, ...
        'y_ticks', [0 120], ...
        'y_tick_decimal_places', 0, ...
        'y_axis_label', {'Stress', '(kN m^{-2})'}, ...
        'y_label_offset', y_label_offsets(1));

text(7.915, 80, {'Isometric','test'}, ...
    'HorizontalAlignment','center', ...
    'FontSize', 9, ...
    'EdgeColor', 'k')

subplot(sp(5));
legendflex(h, {'Low afterload', 'Isometric'}, ...
    'anchor',{'n','s'}, ...
    'xscale', 0.2, ...
    'padding', [3 3 4], ...
    'buffer', [10 -17])

% Output
for i = 1 : numel(output_types)
    figure_export('output_file_string', output_file_string, ...
        'output_type', output_types{i});
end